@startuml
class Class {
    + publicProperty
    # protectedProperty
    - privateProperty
}
abstract class AbstractClass
interface Interface

AbstractClass<|-- Class
AbstractClass..|> Interface

package Package {
    interface Interface2
    abstract class AbstractClass2 implements Interface2
    class Class2 extends AbstractClass2
    enum Enum {
      CASE1
      CASE2
      CASE3
    }
}
@enduml