@startuml
package Lexer {
    interface PumlTokenizer
    package Lexer/Arrow {
        abstract class ArrowTokenizer implements PumlTokenizer
        class LeftArrowTokenizer extends ArrowTokenizer
    }
    package Lexer/CurlyBracket {
        abstract class CurlyBracketTokenizer implements PumlTokenizer
        class OpenCurlyBracketToken extends CurlyBracketTokenizer
    }
}
@enduml