@startuml
package Lexer {
    interface Tokenizeable
    package Lexer/Arrow {
        abstract class ArrowTokenizer implements Tokenizeable
        class LeftArrowTokenizer extends ArrowTokenizer {
            + publicProperty
            # protectedProperty
            - privateProperty
        }
    }
    package Lexer/CurlyBracket {
        abstract class CurlyBracketTokenizer
        class OpenCurlyBracketToken
        
        CurlyBracketTokenizer..|>Tokenizeable
        CurlyBracketTokenizer<|--OpenCurlyBracketToken
    }

    NoneDefinitionClass ..|> Tokenizeable
}
@enduml